enable_cache: False

settings:
  docker:
    required_integrations:
      - mlflow

# Configuration of the Model Control Plane
model:
  name: salary_predictor
  license: Apache 2.0
  description: Predictor of salaries.
  tags: ["regression", "AI", "salary_prediction"]
