FROM python:3.13-slim

WORKDIR /app

# Install build tools and uv, then clean up apt cache
RUN apt-get update && \
    apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/* && \
    pip install uv


COPY . /app

RUN uv pip install --system -r requirements.txt


RUN zenml init

RUN zenml integration install mlflow --uv -y

RUN zenml experiment-tracker register mlflow_tracker --flavor=mlflow && \
    zenml model-deployer register mlflow --flavor=mlflow && \
    zenml stack register local-mlflow-stack -a default -o default -d mlflow -e mlflow_tracker --set


# CMD ["uv", "run", "run_deployment.py"]
# CMD ["sh", "-c", "uv run run_deployment.py; sleep infinity"]

EXPOSE 8501 8000

CMD ["uv", "run", "streamlit", "run", "client.py", "--server.port=8501", "--server.address=0.0.0.0"]