[project]
name = "zenml-project"
version = "0.1.0"
description = "Zenml is an orchestration tool used for machine learning pipelines"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "category-encoders>=2.8.1",
    "zenml[server]>=0.84.1",
]
